Raskraska grafov
ipo-kio/pdf-with-video pull request #2
Opened 2020-07-12 12:44 UTC by praymontana

2020-07-16 11:08 UTC, iposov requested changes
Хорошо получилось с картинками про графы, но в оформлении есть, что исправлять . Посмотрите по комментариям

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +\usepackage{dsfont}
Этот пакет нужен?

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +\usepackage{amssymb}
По-моему, этот пакет не используется

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +\usepackage{svg}
И этот тоже не используется, пока вы не начала вставлять svg изображения

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +	\centering
Всё это, начиная с \centering должно быть внутри окружения \figure. Это актуально здесь и далее. Посмотрите пример оформления картинки в шаблоне конспеста. В вашем случае вместо \includegraphics пишется \tikz, а так всё то же самое. Иначе в плавающую фигуру у вас попадает только заголовок, а сама картинка введена вне плавающей фигуры.

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +		\vspace {0.25 cm}
Этот вертикальный отступ, который вы поставили вручную, станет не нужен после того, как рисунок попадёт в окружение figure.

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +	\tikz{
Рассмотрите вариант вынести всё содержимое \tikz в отдельный файл. Возможно, вам так будет проще писать текст, потому что картинки будут отдельно и не будут его загромождать. Вы будете писать что-то типа \include{graph1.tex}, а внутри graph1.tex находится \tikz{ со всем содержимым.

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +		\flushleft
Здесь и везде эта команда нужна потому, что вы писали \centering вне окружения figure. Теперь у вас \centering вместе с рисунком попадет в figure, и вы не должны будете писать это и явно включать форматирование по левому краю. Кстати, в документе по-умолчанию текст форматируется по ширине, т.ч. \flushleft неправильно отменяла действие \centering.

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +		Эта теорема основывается на принципе \textit{стягивания рёбер}, то есть замены ребра на одну вершину:
не `\textit`, а `\em`, чтобы вместо включения курсива сказать, что здесь вы хотите выделенное слово. И дальше в шаблоне у нас будет автоматически выбираться способ выделения. Курсив или не курсив.

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +	\textbf{Теорема Понтрягина—Куратовского.} Граф является непланарным тогда и только тогда, когда в нём существует подграф, \textit{гомеоморфный} $K_5$ или $K_{3,3}$.
Вы раньше использовали \begin{theorem}[Понтрягина-Куратовского], а сейчас вернулись с выделению жирного заголовка.

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +		Эта теорема основывается на принципе \textit{стягивания рёбер}, то есть замены ребра на одну вершину:
Поищите другие \textit еще по тексту

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +	\textbf{Пример:} Буквы "С" и "Г" гомеоморфны, так как, согнув букву "Г", мы можем получить букву "С". В то же время буква "Т" и буква "С" не гомеоморфны, но гомеоморфны буквы "Т" и "Е".
Либо напишите "Например," без выделения, либо оформите, как раньше оформляли пример через \begin{example*}

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +		В ходе предыдущей лекции было сформулировано два алгоритма: \textit{перемножение матриц} и \textit{алгоритм Уоршалла} и был поднят вопрос, существует ли более эффективный алгоритм. Методом перемнож
Просто мысль. Можно писать N^3 вместо N^{3}, потому что скобки нужны только если вы хотите в степени иметь несколько символов.

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +		Помимо этих двух алгоритмов, существует еще один, связанный с перемножением матриц - алгоритм Штрассена. Он основан на следующей идее: если мы перемножаем матрицы $2\times2$, то на каждый элемент м
Здесь тире. Т.е., во-первых, три минуса, во-вторых, неразрывный пробел перед тире:
`матриц~--- алгоритм Штрассена`

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +		$$
Давайте делать `\[` вместо $$. Соответственно, конец формулы будет `\]`. Тогда я смогу настраивать эту команду, например, добавлять нумерацию в формулы.

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +		Эта идея переносится на произвольные матрицы так: матрица состоит из малых (в нашем случае, матриц $2\times2$), и ее перемножение выглядит таким же образом. Результатом такой работы является трудое
многоточие в данном случае это $\ldots$

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +		Эта идея переносится на произвольные матрицы так: матрица состоит из малых (в нашем случае, матриц $2\times2$), и ее перемножение выглядит таким же образом. Результатом такой работы является трудое
Да, еще в русском десятичная часть числа отделяется запятой. Попробуйте написать запятую, как это будет выглядеть? Я понял, что раньше не разбирался, как в TeX правильно оформлять десятичную часть числа, он может подумать, что это обычная запятая, и поставить после нее длинный пробел. Если плохо выглядит и лень разбираться, верните точку.

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +		Помимо этих двух алгоритмов, существует еще один, связанный с перемножением матриц - алгоритм Штрассена. Он основан на следующей идее: если мы перемножаем матрицы $2\times2$, то на каждый элемент м
Проверьте другие места с дефисом вместо тире.

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +	\vspace{0.25 cm}
Похоже, что вы здесь делаете новый \section. Только много команд для этого, лучше замените \section или \subsection.

Или вы хотите обязательно символ параграфа и номер 9? А в другиех разделах тогда тоже нужна нумерация?

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +	\textbf{Гипотеза:} можно ли любую карту раскрасить четырьмя красками?
Есть \begin{conjecture} у нас для гипотезы. См шаблон, там перечислены все подобные окружения.

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +		\textbf{Решение.} Очевидно, раскрасить двумя красками этот граф невозможно. Тремя же красками можно раскрасить его 6-ю способами (три способа раскрасить первую вершину, два -- вторую и один -- перв
Закончите здесь пример через `\end{example}`. И решение оформите в окружении `\begin{proof}[Решение]`. Я написал в квадратных скобках «решение», чтобы заменить слово «доказательство», которое вставляется по-умолчанию.

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +		\flushleft(Задача о четырех красках)\\
Можно как в теореме пишут название, здесь написать название примера в квадратных скобках `\begin{example*}[Задача о четырех красках]`. Тогда не понадобится даже перевод строки через `\\`

2020-07-16 11:08 UTC, iposov commented on src/Kovaleva/Raskraska grafov
> +		\textbf{Решение.} Приведем классический пример карты для этой задачи (рис.~\ref{fig:map}, a). Данная задача легко сводится к задаче правильной раскраски графа: в каждой области нужно взять по точке
В другом месте показал, как оформить решение вместо слова жирным шрифтом.

2020-08-04 10:30 UTC, iposov commented
Будете добавлять исправления в этот pull request?

2020-08-11 09:27 UTC, praymontana commented
> Будете добавлять исправления в этот pull request?

Да. У меня появились проблемы с добавлением \em вместо \textit (в тексте не только выделяется курсивом слово, но и весь последующий текст становится курсивным). Также у меня смешались рисунки и больше не входят в текст, куда нужно, пока не знаю, как это исправить.

2020-08-11 09:33 UTC, praymontana commented
\documentclass[russian]{lecture-notes}

\usepackage[final]{graphicx}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{tikz}
\usepackage{timestamps}

\title{Раскраска графа}
\lecturer{Поздняков Сергей Николаевич}
\notesauthor{Ковалева Ксения}
\date{29.05.2018}

\begin{document}
	\youtubevideo{Aly9V0rZj6I}
	
	\maketitle
	\section*{Непланарные графы}
	\timestamp{00:00}
	
	Перед тем, как перейти к раскраске графа, рассмотрим понятие непланарных графов.

	\timestamp{00:17}
	\begin{definition} 
		Непланарным графом называется такой граф, который нельзя изобразить на плоскости так, чтобы его ребра не пересекались.
	\end{definition}

	\timestamp{00:13}
	\begin{theorem} [Понтрягина-Куратовского]
		Любой непланарный граф сводится или к полному пятивершинному графу ($K_5$), или к двудольному графу $K_{3,3}$.
	\end{theorem}
		
	Другими словами, иных непланарных графов не существует, то есть внутри любого другого графа можно найти один из двух графов, представленных ниже:\\
	
	\begin{figure}
		\centering
		\tikz{
		\draw (0,0) -- (-0.5,1.5) -- (0.9, 2.5) -- (2.4, 1.5) -- (1.9,0) -- cycle;;
		\draw (0,0) -- (0.9, 2.5);
		\draw (0.9, 2.5) -- (1.9,0);
		\draw (-0.5,1.5) -- (1.9,0);
		\draw (-0.5,1.5) -- (2.4, 1.5);
		\draw (0,0) -- (2.4, 1.5);
		
		\draw [fill=black] (0,0) circle (1 mm);
		\draw [fill=black] (-0.5,1.5) circle (1 mm);
		\draw [fill=black] (0.9, 2.5) circle (1 mm);
		\draw [fill=black] (2.4, 1.5) circle (1 mm);
		\draw [fill=black] (1.9,0) circle (1 mm);
		
		\coordinate [label=above:$1$] (1) at (-0.5,1.6);
		\coordinate [label=right:$2$] (2) at (1, 2.6);
		\coordinate [label=above:$3$] (3) at (2.4,1.6);
		\coordinate [label=right:$4$] (4) at (1.9,0);
		\coordinate [label=left:$5$] (5) at (-0.1,0);
		
		\draw (5,0) -- (5,2.5);
		\draw (7,0) -- (7,2.5);
		\draw (9,0) -- (9,2.5);
		\draw (5,0) -- (7,2.5);
		\draw (5,0) -- (9,2.5);
		\draw (7,0) -- (5,2.5);
		\draw (7,0) -- (9,2.5);
		\draw (9,0) -- (5,2.5);
		\draw (9,0) -- (7,2.5);
		
		\draw [fill=black] (5,0) circle (1 mm);
		\draw [fill=black] (5,2.5) circle (1 mm);
		\draw [fill=black] (7,0) circle (1 mm);
		\draw [fill=black] (7,2.5) circle (1 mm);
		\draw [fill=black] (9,0) circle (1 mm);
		\draw [fill=black] (9,2.5) circle (1 mm);
		
		\coordinate [label=right:$1$] (1) at (5.1,2.5);
		\coordinate [label=right:$2$] (2) at (7.1,2.5);
		\coordinate [label=right:$3$] (3) at (9.1,2.5);
		\coordinate [label=right:$4$] (4) at (5.1,0);
		\coordinate [label=right:$5$] (5) at (7.1,0);
		\coordinate [label=right:$6$] (6) at (9.1,0);
		
		\coordinate [label=below:$K_5$] ($K_5$) at (0.95,-0.5);
		\coordinate [label=right:$K_{3,3}$] ($K_{3,3}$) at (6.5,-0.9);
		}
		\caption{Графы $K_5$ и $K_{3,3}$.}\label{fig:k5k33}
	\end{figure}

	\begin{example*}
		\timestamp{01:18}
		Рассмотрим граф Петерсена.
		
		\begin{figure}
		\centering
		\tikz{
			\draw (0,0) -- (-0.5,1.5) -- (0.9, 2.5) -- (2.4, 1.5) -- (1.9,0) -- cycle;
			\draw (0.25,1.4) -- (1.6,1.4);
			\draw (0.25,1.4) -- (1.35,0.6);
			\draw (1.6,1.4) -- (0.5,0.6);
			\draw (0.9,1.9) -- (1.35,0.6);
			\draw (0.9,1.9) -- (0.5,0.6);
			
			\draw (0.25,1.4) -- (-0.5,1.5);
			\draw (1.6,1.4) -- (2.4, 1.5);
			\draw (0.9,1.9) -- (0.9, 2.5);
			\draw (0.5,0.6) -- (0,0);
			\draw (1.35,0.6) -- (1.9,0);
			
			\draw [fill=black] (0,0) circle (1 mm);
			\draw [fill=black] (-0.5,1.5) circle (1 mm);
			\draw [fill=black] (0.9, 2.5) circle (1 mm);
			\draw [fill=black] (2.4, 1.5) circle (1 mm);
			\draw [fill=black] (1.9,0) circle (1 mm);
			\draw [fill=black] (0.25,1.4) circle (1 mm);
			\draw [fill=black] (1.6,1.4) circle (1 mm);
			\draw [fill=black] (0.9,1.9) circle (1 mm);
			\draw [fill=black] (0.5,0.6) circle (1 mm);
			\draw [fill=black] (1.35,0.6) circle (1 mm);
		}
			\caption{Граф Петерсена.}\label{fig:peterson1}
		\end{figure}
	
		Возникает вопрос: является ли этот граф непланарным? Согласно теореме Понтрягина—Куратовского нужно \textit{выбрать подграф} (иными словами, "выбросить" некоторые ребра графа), а затем, если найдется ребро, на котором есть вершины степени 2, заменить его на ребро с вершинами степени 1 (рис.~\ref{fig:graphs}). 
		
		\begin{figure}
		\centering
		\tikz{
			\draw (-0.5,1.5) -- (2.4,1.5);
			\draw (-0.5,0.5) -- (2.4,0.5);
			\draw [->] (1,1.3) -- (1,0.7);
			
			\draw [fill=black] (-0.5,1.5) circle (1 mm);
			\draw [fill=black] (2.4,1.5) circle (1 mm);
			\draw [fill=black] (1, 1.5) circle (1 mm);
			\draw [fill=black] (-0.5,0.5) circle (1 mm);
			\draw [fill=black] (2.4,0.5) circle (1 mm);
		}
			\caption{Наглядная иллюстрация замены рёбер степени 2.}\label{fig:graphs}
		\end{figure}
	
		Выберем в этом графе, например, подграф вида $K_{3,3}$: для этого нужно связать одну его вершину с тремя другими. Обозначим вершины следующим образом:
		
		\begin{figure}
		\centering
		\tikz{
			\draw (5,0) -- (5,2.5);
			\draw (7,0) -- (7,2.5);
			\draw (9,0) -- (9,2.5);
			\draw (5,0) -- (7,2.5);
			\draw (5,0) -- (9,2.5);
			\draw (7,0) -- (5,2.5);
			\draw (7,0) -- (9,2.5);
			\draw (9,0) -- (5,2.5);
			\draw (9,0) -- (7,2.5);
			
			\draw [fill=black] (5,0) circle (1 mm);
			\draw [fill=black] (5,2.5) circle (1 mm);
			\draw [fill=black] (7,0) circle (1 mm);
			\draw [fill=black] (7,2.5) circle (1 mm);
			\draw [fill=black] (9,0) circle (1 mm);
			\draw [fill=black] (9,2.5) circle (1 mm);
			
			\coordinate [label=right:$x_1$] ($x_1$) at (5.1,2.5);
			\coordinate [label=right:$x_2$] ($x_2$) at (7.1,2.5);
			\coordinate [label=right:$x_3$] ($x_3$) at (9.1,2.5);
			\coordinate [label=right:$y_1$] ($y_1$) at (5.1,0);
			\coordinate [label=right:$y_2$] ($y_2$) at (7.1,0);
			\coordinate [label=right:$y_3$] ($y_3$) at (9.1,0);
		}
			\caption{Обозначение вершин графа $K_{3,3}$.}\label{fig:choose1}
		\end{figure}
		Тогда мы можем обозначить вершины графа Петерсена так же, пользуясь заменами рёбер и ненужных вершин:
		
		\begin{figure}
		\centering
		\tikz{
			\draw (0,0) -- (-0.5,1.5) -- (0.9, 2.5) -- (2.4, 1.5) -- (1.9,0) -- cycle;
			\draw (0.25,1.4) -- (1.6,1.4);
			\draw (0.25,1.4) -- (1.35,0.6);
			\draw (1.6,1.4) -- (0.5,0.6);
			\draw (0.9,1.9) -- (1.35,0.6);
			\draw (0.9,1.9) -- (0.5,0.6);
			
			\draw (0.25,1.4) -- (-0.5,1.5);
			\draw (1.6,1.4) -- (2.4, 1.5);
			\draw (0.9,1.9) -- (0.9, 2.5);
			\draw (0.5,0.6) -- (0,0);
			\draw (1.35,0.6) -- (1.9,0);
			
			\draw [fill=black] (0,0) circle (1 mm);
			\draw [fill=black] (-0.5,1.5) circle (1 mm);
			\draw [fill=black] (0.9, 2.5) circle (1 mm);
			\draw [fill=black] (2.4, 1.5) circle (1 mm);
			\draw [fill=black] (1.9,0) circle (1 mm);
			\draw [fill=black] (0.25,1.4) circle (1 mm);
			\draw [fill=black] (1.6,1.4) circle (1 mm);
			\draw [fill=black] (0.9,1.9) circle (1 mm);
			\draw [fill=black] (0.5,0.6) circle (1 mm);
			\draw [fill=black] (1.35,0.6) circle (1 mm);
			
			\coordinate [label=right:$x_1$] ($x_1$) at (0.9,2);
			\coordinate [label=below:$x_2$] ($x_2$) at (0,-0.1);
			\coordinate [label=below:$x_3$] ($x_3$) at (1.7,1.4);
			\coordinate [label=above:$y_1$] ($y_1$) at (1, 2.5);
			\coordinate [label=right:$y_2$] ($y_2$) at (0.6,0.6);
			\coordinate [label=right:$y_3$] ($y_3$) at (1.36,0.6);
			
			\draw [->] (3,1.4) -- (4,1.4);
			
			\draw (5,0) -- (4.5,1.5) -- (5.9, 2.5) -- (7.4, 1.5);
			\draw [dashed] (7.4, 1.5) -- (6.9,0);
			\draw (6.9, 0) -- (5,0);
			\draw (5.25,1.4) -- (6.6,1.4);
			\draw (5.25,1.4) -- (6.35,0.6);
			\draw (6.6,1.4) -- (5.5,0.6);
			\draw (5.9,1.9) -- (6.35,0.6);
			\draw (5.9,1.9) -- (5.5,0.6);
			
			\draw [dashed] (5.25,1.4) -- (4.5,1.5);
			\draw (6.6,1.4) -- (7.4, 1.5);
			\draw (5.9,1.9) -- (5.9, 2.5);
			\draw (5.5,0.6) -- (5,0);
			\draw (6.35,0.6) -- (6.9,0);
			
			\draw [fill=black] (5,0) circle (1 mm);
			\draw [fill=white] (4.5,1.5) circle (1 mm);
			\draw [fill=black] (5.9, 2.5) circle (1 mm);
			\draw [fill=white] (7.4, 1.5) circle (1 mm);
			\draw [fill=white] (6.9,0) circle (1 mm);
			\draw [fill=white] (5.25,1.4) circle (1 mm);
			\draw [fill=black] (6.6,1.4) circle (1 mm);
			\draw [fill=black] (5.9,1.9) circle (1 mm);
			\draw [ [...]

2020-08-11 11:36 UTC, iposov commented
\em переключает включает выделение до конца группы, поэтому он оформляется чуть иначе, чем \textit: `{\em текст для выделения}`. В отличие от `\texit{текст для выделения}`.

Я исправил несколько `--` на тире `---`, но не уверен, что везде. И загрузил уже в репозиторий. Этот pull request я закрываю, если есть еще какие-то исправления, лучше сделайте новый pull request и исправляйте файл `src/lectures/pozdnkov-dm/graphs-colorings.tex`

2020-08-11 11:36 UTC, closed without merging